### ISSUE TITLE
Int 13h extensions not supported when running produced .bin on virtualbox

### ISSUE THREAD

**Issue by fddnn** [rust-osdev/bootloader#103]
![image](https://user-images.githubusercontent.com/9679893/76617815-fad66400-651e-11ea-89fd-f56d45e5bc5a.png)
?

**Comment by bjorn3** [comment]
Just a wild guess: Is the disk attached as IDE?

**Comment by fddnn** [comment]
no floppy controller would that be the cause of this?

**Comment by RKennedy9064** [comment]
I found some information regarding int 13 extension issues [here](https://stackoverflow.com/questions/56764643/bochs-does-not-support-ah-42h-on-int-13h-on-disk-boot-option). According to that post:

`
Most real computers and Bochs support "int 0x13 extensions" for most/larger devices (hard drives, CD/DVD, etc), but don't support it for floppy disks.
`

So it might be likely that being attached as a floppy disk is what's causing the error.

**Comment by archisgore** [comment]
I got the exact same with a floppy with VMWare. When I wrote it to an HDD, the boot worked.

**Comment by fddnn** [comment]
Ok thanks that fixed it for me.
