### ISSUE TITLE
Don't mask IRQs

### ISSUE THREAD

**Issue by phil-opp** [rust-osdev/bootloader#14]
Currently the bootloader masks all hardware interrupts: https://github.com/rust-osdev/bootloader/blob/bda13d807d0c7451b1ffe74c6c97f6369aef6ff9/src/second_stage.s#L68-L71

They shouldn't be masked when control is passed to the kernel.

**Comment by robert-w-gries** [comment]
Hey Phil, are you saying that interrupts should be enabled when the bootloader jumps to `_start()`?

**Comment by phil-opp** [comment]
No, enabling them would not be a good idea since there isn't an IDT yet. I mean that they shouldn't be _masked_. An interrupt can be masked in the interrupt controller, so that the controller does not emit such an interrupt, even when interrupts are generally enabled.

**Comment by rybot666** [comment]
Since this was patched, can we close the PR?

**Comment by phil-opp** [comment]
@rybot666 Yes, thanks for the hint!
