### ISSUE TITLE
How to connect bootloader to kernel 

### ISSUE THREAD

**Issue by JakubGawron23** [rust-osdev/bootloader#151]
How to properly connect the bootloader with the kernel so that the `` entry_point! '' Macros can be used
![Zrzut ekranu (9)](https://user-images.githubusercontent.com/76694285/115198490-66abd880-a0f2-11eb-874a-e5169b886c4b.png)

**Comment by phil-opp** [comment]
What error message are you seeing?

**Comment by JakubGawron23** [comment]
My point is how to link the bootloader as a folder and not as a dependency in Cargo.toml.

**Comment by phil-opp** [comment]
You mean that you cloned the bootloader locally and want to use that folder as a dependency instead of crates.io? In that case, you can specify a [path dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies) in your Cargo.toml.

**Comment by JakubGawron23** [comment]
I added the path to Cargo.toml and ran all the commands and got such an error, how to fix it?
![Zrzut ekranu (10)](https://user-images.githubusercontent.com/76694285/115217728-13438580-a106-11eb-8a0f-c02c2d036e7c.png)

**Comment by JakubGawron23** [comment]
However, the problem was solved :)

**Comment by phil-opp** [comment]
Great to hear that!
