### ISSUE TITLE
`0xdeadbeef` causes page fault on higher half

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [rust-osdev/bootloader#163]
According to Osdev wiki:
> 'Mnemonic' invalid pointers such as 0xCAFEBABE, 0xDEADBEEF, 0xDEADC0DE, etc. can be used on higher half kernels.

<https://wiki.osdev.org/Higher_Half_Kernel>

```rust
unsafe {
    *(0xdeadbeef as *mut u32) = 32;
}
```

 Only address like `0xcafebabedeadbeef` should cause page faults on higher half.

cc @phil-opp

**Comment by phil-opp** [comment]
Every pointer will cause a page fault unless it points to a page that is mapped in the page tables. If you use a higher-halft kernel, the lower half is not mapped, except for few special memory mappings created by the bootloader. So it is expected that a page fault occurs in that case.

I think you misunderstood the OSDev article you linked. For one, they were talking about 32-bit kernels that are mapped to the address range 0xC0000000 – 0xFFFFFFFF. Second, they don't mean that you can randomly access all pointers in that region, only that you are able to map such easy-to-remember pointers to use them for something special (e.g. a mapped dummy element in a linked list).
