### ISSUE TITLE
Bootloader `v0.9.17` seems to be broken on Rust `nightly-2021-05-20`

### ISSUE THREAD

**Issue by phil-opp** [rust-osdev/bootloader#167]
I just noticed this in the automated CI runs for the `blog_os` project: https://github.com/phil-opp/blog_os/runs/2626134888?check_suite_focus=true#step:12:47

When trying to run `cargo +nightly-2021-05-20 run`, the following error occurs:

![image](https://user-images.githubusercontent.com/1131315/118969024-e08ee600-b96c-11eb-894c-c3ab3a738583.png)

The error message is "Failed to load rest of bootloader" and happens in the early assembly stages.

I'm not sure what's going wrong yet, I will update this issue when I find the cause.

**Comment by phil-opp** [comment]
Diff between the working and broken nightly: https://github.com/rust-lang/rust/compare/4e3e6db01...f94942d84

**Comment by bjorn3** [comment]
`--gc-sections is now only passed if `"linker-is-gnu": true` is used inside the target spec. The blog os target spec doesn't mention it. Maybe the first stage is too big without `--gc-sections`?

**Comment by phil-opp** [comment]
@bjorn3 Ah thanks, I think that's likely the reason. I'll push a fix in a moment.

**Comment by phil-opp** [comment]
I opened #168 with a fix.

**Comment by phil-opp** [comment]
Fix published as v0.9.18. A `cargo update -p bootloader` should be enough to fix this issue in downstream crates.
