### ISSUE TITLE
How could I use uefi-rs and bootloader together?

### ISSUE THREAD

**Issue by actuallyexeon** [rust-osdev/bootloader#183]
I'm trying to print some text on the screen using UEFI but my project uses bootloader and AFAIK I don't think you can use a different function for uefi-rs other than efi_main, is there any way I can accomplish this somehow?

**Comment by ethindp** [comment]
No, you can't. The `uefi_main`/`efi_main` function is the only way to get access to EFI boot services. The bootloader exits boot services *before* calling `kmain` so this is not possible.

**Comment by actuallyexeon** [comment]
So how would I go about printing text on the screen or something like that without the uefi-rs crate

**Comment by ethindp** [comment]
@actuallyexeon You need to use the framebuffer that the bootloader gave you. I'm not too sure on the maths required -- I can't really figure that out myself (but would love to know how) -- and though the OSDev wiki has [this article](https://wiki.osdev.org/Drawing_In_a_Linear_Framebuffer) I didn't consider it much help. But maybe you'll find it of use.
