### ISSUE TITLE
Error compiling with "cargo bootimage"

### ISSUE THREAD

**Issue by spocino** [rust-osdev/bootloader#188]
When trying to compile a project using bootimage, I get an error as such:

```
Error: An error occured while trying to build the bootloader: The `bootloader` dependency has not the right format: No `package.metadata.bootloader.target` key found in Cargo.toml of bootloader

(If you're using the official bootloader crate, you need at least version 0.5.1)

Caused by:
    The `bootloader` dependency has not the right format: No `package.metadata.bootloader.target` key found in Cargo.toml of bootloader
    
    (If you're using the official bootloader crate, you need at least version 0.5.1)
```

I am using bootloader version `0.10.6`, and the latest bootimage package.

**Comment by NathanMcMillan54** [comment]
Try looking at [this](https://github.com/rust-osdev/bootloader#usage)

**Comment by phil-opp** [comment]
The `bootimage` crate is no longer used with `v0.10` and `v0.11` of the bootloader. See also our migration guides: https://github.com/rust-osdev/bootloader/tree/main/docs/migration
