### ISSUE TITLE
Printing to VGA crashes qemu

### ISSUE THREAD

**Issue by Brian3647** [rust-osdev/bootloader#198]
Sample code: https://github.com/Brian3647/rust-bootloader-issue

**Comment by bjorn3** [comment]
Bootloader 0.10 doesn't use vga text mode anymore. It sets up a framebuffer instead whose address is stored in `boot_info.framebuffer`. You have to rasterize a font and write the raw pixels or use the serial port instead.

**Comment by Brian3647** [comment]
@bjorn3 do you know any tutorial or something I can follow to do that?

**Comment by Brian3647** [comment]
@bjorn3 thanks!
