### ISSUE TITLE
Potential UB upon entering unreal mode

### ISSUE THREAD

**Issue by refarb** [rust-osdev/bootloader#241]
According to [the reference](https://doc.rust-lang.org/nightly/reference/inline-assembly.html#rules-for-inline-assembly) all registers not mentioned as clobbered by a block (by using `out("<reg>") _`) **must** have the same (undefined) value they had when entering the block when the asm block ends, "otherwise behavior is undefined".

However, both [line 76](https://github.com/rust-osdev/bootloader/blob/785e82a119d359edd93ef7fc9fc72a7e00f7c9da/bios/second_stage/src/protected_mode.rs#L76) and [line 85](https://github.com/rust-osdev/bootloader/blob/785e82a119d359edd93ef7fc9fc72a7e00f7c9da/bios/second_stage/src/protected_mode.rs#L85) of `enter_unreal_mode` in the second stage of the bootloader modify registers without stating this to the compiler.

Because I have never programmed any processor, except microprocessors without differing execution modes, I am unsure if this is actually fine (because upon switching into unreal mode all registers are to be considered clobbered for some reason? But then that would also require marking at least one asm block for the compiler?) or an actual bug which causes UB and should be fixed.

**Comment by phil-opp** [comment]
Thanks a lot for reporting! You're right that this was probably undefined behavior and should have been fixed. Sorry for not reacting earlier!

I think we no longer have this problem with #232 merged, so I think we can close this. Please let me know if you see any similar issue with the current implementation!
