### ISSUE TITLE
undefined symbol: _fltused

### ISSUE THREAD

**Issue by Skyslycer** [rust-osdev/bootloader#244]
Hi, I just cloned the basic example, ran `cargo kimage`, and got this error: https://paste.skyslycer.de/JUT6Y

**Comment by bjorn3** [comment]
Try updating rustc. There was a bug in rustc a couple of days ago that is now fixed.

**Comment by Skyslycer** [comment]
Will try, thank you.

**Comment by Skyslycer** [comment]
That worked!
