### ISSUE TITLE
issue with cargo krun in basic example

### ISSUE THREAD

**Issue by Skyslycer** [rust-osdev/bootloader#245]
Hi again, I cloned the basic example (and renamed `simple_boot` to `runner`) and wanted to run it with `cargo krun`. This however produced this error: https://paste.skyslycer.de/UELpM

I can't seem to figure it out. I probably have missed something.

Thanks in advance!

**Comment by Freax13** [comment]
The crash seems to come from here: https://github.com/rust-osdev/bootloader/blob/ac46d0455b41c11e5d316348d068df1c495ce0af/examples/basic/simple_boot/src/main.rs#L31-L37

You might have to change the path to `qemu-system-x86_64` to work with your environment.

**Comment by Skyslycer** [comment]
> The crash seems to come from here:
> 
> https://github.com/rust-osdev/bootloader/blob/ac46d0455b41c11e5d316348d068df1c495ce0af/examples/basic/simple_boot/src/main.rs#L31-L37
> 
> You might have to change the path to `qemu-system-x86_64` to work with your environment.

The path of the qemu file?

**Comment by Freax13** [comment]
Huh, no, actually we also do the same in the tests and those run fine in CI on windows:
https://github.com/rust-osdev/bootloader/blob/ac46d0455b41c11e5d316348d068df1c495ce0af/examples/test_framework/boot/src/main.rs#L42-L45

Do you have QEMU installed?

**Comment by Skyslycer** [comment]
Yea, I have all the QEMU files including the exe in my Program Files

**Comment by Freax13** [comment]
Is QEMU in the PATH environment variable?

**Comment by Skyslycer** [comment]
Yes, it is.

**Comment by Skyslycer** [comment]
Okay, seems to work after a restart. Idk. Thanks for the help though.
