### ISSUE TITLE
No longer starts the VGA in text mode

### ISSUE THREAD

**Issue by OleStrohm** [rust-osdev/bootloader#249]
I just updated from pre-0.10, and now the vga starts in a graphics mode, which makes it more difficult to get start printing simple things.

I looked through the features, but I couldn't find any reference to a text mode, so has it been removed entirely?

**Comment by bjorn3** [comment]
Yes, it has been removed UEFI doesn't support text mode, so to allow using the same kernel code on BIOS and UEFI, bootloader now sets up a framebuffer unconditionally.

**Comment by phil-opp** [comment]
We now have some [migration guides](https://github.com/rust-osdev/bootloader/tree/main/docs/migration) that explain how to switch from VGA text mode to a framebuffer.
