### ISSUE TITLE
map-physical-memory in 0.10.12

### ISSUE THREAD

**Issue by asensio-project** [rust-osdev/bootloader#253]
Hello, 

I tried to use the map-physical-memory feature of the bootloader but it's not present, is there a replacement or a similar function in the current version?

**Comment by AmberCrafter** [comment]
![image](https://user-images.githubusercontent.com/39610187/187031686-9c5ef1a0-1115-4b75-9e50-c46b8f92dc74.png)

You can find more detail from here: https://docs.rs/bootloader/latest/bootloader/struct.Config.html.

**Comment by asensio-project** [comment]
Thanks!
