### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by asensio-project** [rust-osdev/bootloader#254]
Hello,

I tried to compile my kernel with version 0.10.12 of this crate with the "rustc 1.65.0-nightly (eaadb8947 2022-08-27)" but I get:
LLVM ERROR: dwo only supported with ELF and Wasm
error: could not compile `rustc-std-workspace-core`
warning: build failed, waiting for other jobs to finish...
LLVM ERROR: dwo only supported with ELF and Wasm
error: could not compile `core`
LLVM ERROR: dwo only supported with ELF and Wasm
error: could not compile `compiler_builtins`.

I can compile it with rust 1.63.0-nightly.

**Comment by Freax13** [comment]
https://github.com/rust-lang/rust/issues/101071

**Comment by asensio-project** [comment]
Closing as a duplicate.
Thanks.
