### ISSUE TITLE
`bootloader` dependency has not the right format: No `package.metadata.bootloader.target` key found in Cargo.toml of bootloader

### ISSUE THREAD

**Issue by saivishwak** [rust-osdev/bootloader#270]
Finished dev [unoptimized + debuginfo] target(s) in 4.80s
Error: An error occured while trying to build the bootloader: The `bootloader` dependency has not the right format: No `package.metadata.bootloader.target` key found in Cargo.toml of bootloader

(If you're using the official bootloader crate, you need at least version 0.5.1)

Caused by:
    The `bootloader` dependency has not the right format: No `package.metadata.bootloader.target` key found in Cargo.toml of bootloader

    (If you're using the official bootloader crate, you need at least version 0.5.1)

**Comment by saivishwak** [comment]
With latest rust nightly the issue is seen.

**Comment by bjorn3** [comment]
Can you post the `Cargo.toml` file you are using?

**Comment by saivishwak** [comment]
[package]
name = "rob_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.10.13"

[package.metadata.bootimage]
build-command = ["build"]

**Comment by bjorn3** [comment]
If you are following https://os.phil-opp.com you will have to use bootloader version 0.9, not 0.10.

**Comment by saivishwak** [comment]
Oh Okay, Thanks a lot. Was getting a linker error in 0.9.8 in latest nightly so switched to 0.10.13.

**Comment by phil-opp** [comment]
See https://github.com/rust-osdev/bootloader/issues/271 for details on that linker error. It's a regression in Rust and should be resolved in a few days.
