### ISSUE TITLE
UEFI v 0.11 is failing to detect the `bootloader_api` version

### ISSUE THREAD

**Issue by kennystrawnmusic** [rust-osdev/bootloader#277]
In the process of attempting to port my kernel to version 0.11 of the bootloader crate and managed to get it to successfully compile — ah, but when I try to run it I get this (using version 0.1.0-alpha.0 of bootloader_api):
<img width="1440" alt="Screenshot 2022-11-12 at 9 16 31 AM" src="https://user-images.githubusercontent.com/3030773/201486447-1ce2cb02-8431-458d-8180-71fbed4f5c1d.png">

Note that instead of stating the version as the correct `0.1.0-alpha.0` it's stating the version as `()` (the unit type). Why would this be?

**Comment by Freax13** [comment]
The function for deserializing the configuration doesn't have a proper error type yet:
https://github.com/rust-osdev/bootloader/blob/next/api/src/config.rs#L151

**Comment by phil-opp** [comment]
Thanks for reporting! I created a fix in #280.
