### ISSUE TITLE
UEFI: Frame allocation fails when mapping a kernel stack larger than 66MB

### ISSUE THREAD

**Issue by kennystrawnmusic** [rust-osdev/bootloader#284]
When setting `CONFIG.mappings.kernel_stack_size` to a larger value than 66 megabytes, this happens: 
![image](https://user-images.githubusercontent.com/3030773/202647266-523b5bbf-61d2-4bbc-bc14-1daa7c5103de.png)

Not sure why this is, but definitely something that needs to be looked into, especially as kernels increase in complexity and need proper page alignment for an ever-increasing number of tasks.

**Comment by Freax13** [comment]
That's an out of memory error, how much RAM did you assign the VM?

**Comment by kennystrawnmusic** [comment]
Alright, adding `-m 4G` to the list of arguments that my runner crate passes to QEMU did increase the point at which this occurs. Closing
