### ISSUE TITLE
Building recompiles bootloader every build, resulting in extreme build times

### ISSUE THREAD

**Issue by BigBadE** [rust-osdev/bootloader#286]
Following the docs and making a simple project, a basic OS takes over 2 minutes to compile.

How to replicate:
- Pull https://github.com/BigBadE/RustOS/commit/3bb04913239c076c5ead8129cfdda12c72251d5b (simple project, or just follow the tutorial for making one)
- Follow setup and run ```cargo run``` once to pull dependencies
- Build again with no changes, and compilation will take 2-4 minutes, always freezing on bootloader

Looking around Cargo issues, it looks like this issue has been reported a few times in the past (https://github.com/rust-lang/cargo/issues/1162, https://github.com/rust-lang/cargo/pull/1714, https://github.com/gimli-rs/cpp_demangle/issues/79), but I didn't find any relevant reported issues. This build time makes running/testing extremely difficult.

**Comment by BigBadE** [comment]
Adding onto this:

- Cloning bootloader and depending on it locally doesn't have this issue.
- Using latest bootloader and bootloader_api.

**Comment by phil-opp** [comment]
Thanks for reporting! I pushed a fix to #286, which should solve this. Could you try again with the `v0.11.0-beta.4` release?

**Comment by BigBadE** [comment]
Confirmed fixed in beta.4
