### ISSUE TITLE
Add a QUIET feature

### ISSUE THREAD

**Issue by asensio-project** [rust-osdev/bootloader#288]
Hello, 

I think that would be good idea adding a cargo feature for avoiding the bootloader to print messages in the screen until loading the kernel.
This way we don't need to clear the screen before printing messages.

Thanks.

**Comment by Freax13** [comment]
Note that you might have to clear the screen anyways because some BIOS' will show the manufacturers logo on startup.

**Comment by asensio-project** [comment]
A published a new PR #303.
It's ready for review.
