### ISSUE TITLE
Failed to load rest of bootloader

### ISSUE THREAD

**Issue by acheronfail** [rust-osdev/bootloader#30]
I'm getting the following error when I try to build and run this bootloader:

![image](https://user-images.githubusercontent.com/34289614/48962512-112c7980-efd5-11e8-8ca9-0acecf9512eb.png)

FWIW this happens both on linux (ubuntu 18.10) as well as on macOS (10.14).

Any pointers you can give me for debugging this?

**Comment by phil-opp** [comment]
I think this should be solved by #34. The problem was probably that you didn't include the kernel info block.

**Comment by acheronfail** [comment]
Yep, you're right. 👍 
I've tested the changes in #34 and it all works now.

**Comment by phil-opp** [comment]
Perfect, thanks for testing!
