### ISSUE TITLE
Terminal blocked after cargo test

### ISSUE THREAD

**Issue by asensio-project** [rust-osdev/bootloader#338]
Hello,

After I execute ``cargo test`` the STDOUT of my terminal blocks, so I cannot see what I am writing. This happens after #333. I think that it's an unclosed pipe  in the run_qemu() function, but I don't know anything more.

I am working for fixing it. And I will publish a PR. But if someone knows something...

Thanks!

**Comment by phil-opp** [comment]
You mean while `cargo test` runs? Or still afterwards?

In case you mean the former: that's probably because we're forwarding stdin to QEMU. Let me try to fix this.

**Comment by phil-opp** [comment]
I opened https://github.com/rust-osdev/bootloader/pull/339 to set `stdin` to `null` for the QEMU command. Could you try whether this fixes your issue?

**Comment by asensio-project** [comment]
I tried it, and it fixes it. Thanks!
