### ISSUE TITLE
When I use latest version 0.11 custom target does not compile saying std not supported

### ISSUE THREAD

**Issue by foragerDev** [rust-osdev/bootloader#374]
I am trying to compile [A minimal Rust Kernel](https://os.phil-opp.com/minimal-rust-kernel/#set-a-default-target) with latest version 0.11, It does not work complains for std not supported for custom target but when I compile with version 0.9.8 it works. Can you explain what's wrong with it?

**Comment by bjorn3** [comment]
Blog os currently requires bootloader 0.9. After version 0.9 there has been significant changes in the way that it works. The third edition of blog os, which is currently being written, uses bootloader 0.11.

**Comment by foragerDev** [comment]
Oh, Thanks for clarification. 👍🏼
