### ISSUE TITLE
Cannot compile version 0.11.3

### ISSUE THREAD

**Issue by DecrepitHuman** [rust-osdev/bootloader#375]
I've followed the quick start provided in this repo (https://github.com/rust-osdev/bootloader/blob/HEAD/docs/create-disk-image.md)
I've got the exact dependencies, files, directories, layout and so on. I'm compiling to `x86_64-unknown-none` with rustc version 1.71.0-nightly in WSL2 (Ubuntu)

I get the following output: https://sourceb.in/2wDVzkJ4ZV
I have LLVM15 installed and in my PATH (`llvm-config --version` shows 15.0.7)

**Comment by bjorn3** [comment]
Have you installed the `llvm-tools` rustup component using `rustup component add llvm-tools`? Bootloader's build script looks for the objcopy llvm tool exclusively in the rustc toolchain, not in your `PATH`.

**Comment by DecrepitHuman** [comment]
That fixed it. I can't recall reading anywhere that I needed to do this, but I know for a fact that I wasn't reading everything. Thank you, it's now compiling
