### ISSUE TITLE
Some logs still show even with logs turned off 

### ISSUE THREAD

**Issue by interstellarfrog** [rust-osdev/bootloader#387]
when turning all logs off using the following code:

```Rust
    use bootloader::BootConfig;
    use bootloader_boot_config::LevelFilter;

    let mut boot_config = BootConfig::default();

    boot_config.serial_logging = false;
    boot_config.frame_buffer_logging = false;
    boot_config.log_level = LevelFilter::Off;
```

Some logs still show on the screen this is only for BIOS builder UEFI seems to works fine

Serial is working as expected no output even when serial logging is on and `log_level = Off`

But some logs are printed to the framebuffer no matter what

Using version 0.11.4 for all dependencies tested on 0.11.3 same results

**Comment by asensio-project** [comment]
Hi. The log_level only disables logs on the Framebuffer.
UEFI  only uses the Framebuffer.
BIOS is old fashioned and it also uses the VGA driver for displaying logs.

When we created the log_level, we didn't modify that. The old system is necessary for displaying logs early in the boot process.
