### ISSUE TITLE
Bootloader marks frames used for the ramdisk as MemoryRegionKind::Usable when using Uefi

### ISSUE THREAD

**Issue by daniel-keitel** [rust-osdev/bootloader#399]
Frames in which the ramdisk is stored may be reported as usable in a memory region, when using Uefi.

Tested on hardware (i9-13900K) and qemu.

Workaround:
 - get physical address range of ramdisk (should be contiguous)
 - prevent frames in this range from being used

**Comment by phil-opp** [comment]
Thanks a lot for reporting! I prepared a fix in https://github.com/rust-osdev/bootloader/pull/408.
