### ISSUE TITLE
Is it possible to support ARM in this crate?

### ISSUE THREAD

**Issue by shinobu-uwu** [rust-osdev/bootloader#456]
Hello, I hope everyone is okay.

I am creating a kernel that I plan to run in a raspberry Pi, which has ARM architecture and I know that ARM is still not supported in this crate, but I wanted to ask if it is possible to implement in this crate instead of creating a new one, and how hard would that be? I can implement it myself, since I would have to anyways, that's why I'm reaching you out. Also if I have any doubts what is the best channel to ask them?

**Comment by bjorn3** [comment]
If you were to use u-boot, then having this crate be a uefi bootloader for arm would be feasible I think. Handling all the custom boot protocols arm systems that don't support uefi have would probably be pretty hard.
