### ISSUE TITLE
Hang after loading first level 4 table on uefi

### ISSUE THREAD

**Issue by Colepng** [rust-osdev/bootloader#462]
I tried my os on real hardware for the first time and found that the bootloader is hanging. I tracked the issue down to this [line](https://github.com/rust-osdev/bootloader/blob/fffa7ceb317328ed19bc0ebaa0028be152095a05/uefi/src/main.rs#L336-L339). I'm still a beginner in os development so any help is appreciated.

I am running it on my laptop which is a lenvo legion 7 which has a AMD Ryzen 7 5800H.

**Comment by Freax13** [comment]
Hmm, there's not much to go on. How did you track this hang down to this line? Can you share the log output?

**Comment by Colepng** [comment]
I cloned the repo locally, linked my kernel to the local version and added debug statements. I put 1 statement after the line I linked to and 1 after. Only the first 1 ran. The best photo I can add would be from my phone.

![Image](https://github.com/user-attachments/assets/1967a977-89ca-4fdf-81a0-379507cc2547)

As you can see in the photo it no longer hang. Instead of only copying over the first entry of the old page table, I started copying over all entries and now it works. The panic you can see in the photo seems to be from the fact my system uses huge page table while the bootloader expects 4KiB tables. If you know, could you explain to me why copying over all the old entries would fix it.

**Comment by Freax13** [comment]
The frame buffer (0xfc_1000_0000) is address is in the second pml4 entry, interesting, so the assumption in the comment was incorrect. Your fix seems reasonable. Freel free to open at PR.
