### ISSUE TITLE
Question: how to boot the linux kernel with the bootloader?

### ISSUE THREAD

**Issue by pheonixfirewingz** [rust-osdev/bootloader#463]
As stated in the title I’m making this issue/question as I would like to make my own distro without using grub two And from what I could find, there is no instructions in the repository. Could someone kindly give me a clue or tell me how to achieve this goal, thank you.

**Comment by bjorn3** [comment]
This crate uses it's own bootloader protocol that isn't supported by Linux.

**Comment by zatrit** [comment]
Hypothetically you have to write a Rust wrapper for the Linux kernel
