### ISSUE TITLE
`log::info!` called before initializing logger

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [rust-osdev/bootloader#475]
https://github.com/rust-osdev/bootloader/blob/af99f0f9e913cb9741d47de457b942f706f79625/uefi/src/main.rs#L534

This line doesn't do anything write now. It basically functions as a comment. It should either be
- Removed
- Moved to be after calling `init_logger` (I don't think it's necessary since https://github.com/rust-osdev/bootloader/blob/af99f0f9e913cb9741d47de457b942f706f79625/uefi/src/main.rs#L115
- Turned into a comment

**Comment by Freax13** [comment]
Makes sense, feel free to open a PR.
