### ISSUE TITLE
Make builder executable available as binary?

### ISSUE THREAD

**Issue by timClicks** [rust-osdev/bootloader#48]
Would you consider adding the builder executable to a `[[bin]]` section of the cargo manifest a good idea? That should simplify things for people who don't want to clone the repo and manually `cd` into the builder directory to make use of it.

If so, I'm happy to whip up the short PR

**Comment by phil-opp** [comment]
That's a good idea, but I'm not sure how it would work with the dependencies. The builder crate uses some dependencies that rely on the standard library, which we can't use for the rest of the bootloader. AFAIK there is currently no way to define dependencies only for a specific binary. Maybe we can work around it by (ab)using cargo's [platform specific dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) somehow.
