### ISSUE TITLE
Cargo warning about `publish-lockfile` feature when compiling

### ISSUE THREAD

**Issue by luojia65** [rust-osdev/bootloader#57]
Hello! When I test an handwritten OS following the toturial _Writing an OS in Rust_, the test is successful, but there is a warning on configuration when building the bootloader. Here's my console output:
```
PS D:\RustProjects\spicy_os> cargo xtest
   Compiling spicy_os v0.1.0 (D:\RustProjects\spicy_os)
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running target\x86_64-spicy_os\debug\deps\spicy_os-990499773c553c1e
Building bootloader
warning: The `publish-lockfile` feature is deprecated and currently has no effect. It may be removed in a future version.
   Compiling bootloader v0.6.0 (C:\Users\luojia65\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\bootloader-0.6.0)
    Finished release [optimized + debuginfo] target(s) in 1.88s
Running: `qemu-system-x86_64 -drive format=raw,file=D:\RustProjects\spicy_os\target\x86_64-spicy_os\debug\deps\bootimage-spicy_os-990499773c553c1e.bin -device isa-debug-exit,iobase=0xf4,iosize=0x04 -serial stdio -display none
```
According to this warning, cargo feature `publish-lockfile` has currently no effect. It looks like this is related to the piece of code [here](https://github.com/rust-osdev/bootloader/blob/f770e97f6c52420212ff69e7acfec6b4854a46ff/Cargo.toml#L1). Would it be possible to remove this cargo feature configuration, or do another way to fix this warning? 

Here's my Rustup and Rustc version:
```
C:\Users\luojia65>rustup -V
rustup 1.18.3 (435397f48 2019-05-22)

C:\Users\luojia65>rustc -V
rustc 1.35.0 (3c235d560 2019-05-20)
```

**Comment by phil-opp** [comment]
Thanks for reporting! The `publish-lockfile` feature was recently removed in https://github.com/rust-lang/cargo/pull/7026. So yes, removing the cargo feature should fix the warning. However, I think we should wait for a bit (about a week or so) before removing the feature to give people that rely on the `publish-lockfile` feature time to update their nightlies.
