### ISSUE TITLE
Failed to load second stage of bootloader

### ISSUE THREAD

**Issue by phodina** [rust-osdev/bootloader#6]
The booloader fails to load the second stage when run in qemu. In func load_second_stage_from_disk in file boot.s the code jumps to label second_stage_load_failed as the carry flag has been set.

**Comment by phil-opp** [comment]
You have to compile in release mode. Not sure why yet, but I assume that it grows too big otherwise.

**Comment by phodina** [comment]
I tried the release mode as you suggested but it also failed to load second stage.

Commands:
```
RUST_TARGET_PATH=`pwd` xargo run --target x86_64-bootloader --release
objcopy -O binary -S target/x86_64-bootloader/release/bootloader target/bootloader.bin
qemu-system-x86_64 -hda target/bootloader.bin -d int -s
```

**Comment by rybot666** [comment]
Also seems solved, can we close this

**Comment by phil-opp** [comment]
Agreed, but we definitely need to provide documentation for this.
