### ISSUE TITLE
Compiling with "binary" feature with example kernel fails

### ISSUE THREAD

**Issue by ethindp** [rust-osdev/bootloader#76]
When building the bootloader as a dependency (i.e. to enjoy the extra features) the build fails:
```
thread 'main' panicked at 'The bootloader must be compiled for the `x86_64-bootloader.json` target.', C:\Users\ethin\.cargo\registry\src\github.com-1ecc6299db9ec823\bootloader-0.8.0\build.rs:108:9
```
I am attempting to take advantage of the dynamic stack selection, dynamic kernel placement, etc., that I would not otherwise enjoy had I not specified the "binary" feature. Is this doable?

**Comment by phil-opp** [comment]
The `binary` feature should only be specified if you compile the bootloader as a binary. if it is a dependency in your Cargo.toml, you compile it as a library and should not add the feature.

The `bootimage` tool automatically sets the `binary` feature when it compiles the bootloader binary. Just use the latest bootloader version and you get all the benefits you mentioned.

**Comment by phil-opp** [comment]
Seems to be answered. If this is still a problem for you, let us know!
