### ISSUE TITLE
Building error when kernel filename containing special characters

### ISSUE THREAD

**Issue by midwinter1993** [rust-osdev/bootloader#93]
Hi all,

A building error occurs when renaming the kernel binary and building

```bash
cp example-kernel/target/x86_64-example-kernel/debug/example-kernel example-kernel/target/x86_64-example-kernel/debug/example-kernel.elf

KERNEL=example-kernel/target/x86_64-example-kernel/debug/example-kernel.elf KERNEL_MANIFEST=example-kernel/Cargo.toml cargo xbuild --release --features binary
```

Error: `rust-lld: error: undefined symbol: _kernel_start_addr`.

It seems that `build.rs` does not redefine the symbols correctly, i.e., `_binary_objfile_*` set by `objcopy`, when objfile name contains the special character `.`.

**Comment by phil-opp** [comment]
Thanks for reporting this!

I created a fix in #94. Could you verify if it works for you?

**Comment by midwinter1993** [comment]
Hi @phil-opp,

Great! It works for me now.

**Comment by phil-opp** [comment]
Thanks for verifying!
