### ISSUE TITLE
Enable tls sections

### ISSUE THREAD

**Issue by vinaychandra** [rust-osdev/bootloader#95]
`tdata` and `tbss` section stores thread local storage for the system. In kernel, we will need to initialize this section per-cpu or per-thread depending on usages. Rust provides a `#[thread_local]` attribute which puts the data in the above sections.

Please enable that section in bootloader and pass its location to the kernel so that it can map the TLS data as needed.

**Comment by phil-opp** [comment]
Could you clarify what you mean with "enable that section"? Do you mean to just load and map it into the virtual memory or are there any additional required steps?

**Comment by vinaychandra** [comment]
Just mapping into memory and then providing location is enough.
[This](https://gitlab.redox-os.org/redox-os/kernel/blob/master/src/arch/x86_64/paging/mod.rs#L202) is an example of how it could be loaded later in kernel
