### ISSUE TITLE
BootInfo address appears to be erroneously set to 0x10000000000

### ISSUE THREAD

**Issue by zesterer** [rust-osdev/bootloader#98]
Causing a page fault upon attempted access, of course.

**Comment by phil-opp** [comment]
@zesterer Thanks for reporting! Do you have your code online somewhere so that I can try to reproduce it?

**Comment by zesterer** [comment]
You can see this happening with https://github.com/tupai-os/deus.

Relevant code is here: https://github.com/tupai-os/deus/blob/master/src/arch/x86_64/mod.rs#L12

and here: https://github.com/tupai-os/deus

**Comment by phil-opp** [comment]
Thanks! I just tried it and it seems like the boot info is really at this address. Accessing it works without problems for me. Try inserting `logln!("BootInfo: {:#?}", info);` at the beginning of your `kernel_start` function.

**Comment by zesterer** [comment]
How bizarre. This definitely wasn't working before. Sounds like I've got a spurious issue to fix! Thanks for the rapidly response.

**Comment by phil-opp** [comment]
No problem! Let me know if you encounter this issue again.
